application:
  properties:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hovall_prototype?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file:
    path: E:/enterprise
    name: prototype.log
server:
  port: 8080
