spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hovall_prototype?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2021JavaForTest@gmail.com
    password: forTest2021
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true


logging:
  file:
    path: E:/enterprise
    name: prototype.log
server:
  port: 8090
